name: A TO A:GH_PAGES
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: hardocs/hardocs.github.io@develop
      env:
        ACCESS_TOKEN: ${{ secrets.SECRET_TOKEN }}
        TARGET_REPO: hardocs/hardocs.github.io
        TARGET_BRANCH: gh_pages
        BUILD_SCRIPT: yarn && yarn build
        BUILD_DIR: build